name: Rust build & tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: debianmaster/actions-k3s@master
        id: k3s
        with:
          version: 'latest'
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Clippy
        run: cargo clippy --verbose
      - name: Run tests
        run: cargo test --verbose